version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: conference_app_user
      POSTGRES_PASSWORD: 5UvUwY3xRH86xXhx
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
